#
# vi should "set expandtab&". Makefile cmds require tab
#
# init-jobs:     init the jobs in the $JOBS var found in  jobs.config
# run-jobs:      run the jobs list 
# clean-jobs:    clean all artifacts generated by init-jobs and run-jobs, but not run dirs
#
# init-all:     init ALL dirs under REGULUS
# run-all:      run all dirs 
# clean-all:    clean all artifacts generated by init-all and run-all, but not run dirs
#

include ./jobs.config
SHELL := /bin/bash

.PHONY: confirm_execute

init-jobs:
	echo JOBS=$JOBS
	@for dir in $(JOBS); do \
		echo "Executing script in $$dir"; \
		$(MAKE) -C $$dir init; \
	done

clean-jobs:
	echo JOBS=$JOBS
	@for dir in $(JOBS); do \
		echo "Executing script in $$dir"; \
		$(MAKE) -C $$dir clean; \
	done

run-jobs:
	echo JOBS=$JOBS
	@for dir in $(JOBS); do \
		echo "Executing script in $$dir"; \
		$(MAKE) -C $$dir run; \
	done

dry-run-jobs:
	echo JOBS=$JOBS
	@for dir in $(JOBS); do \
		echo "Executing script in $$dir"; \
		$(MAKE) -C $$dir dry-run; \
	done

confirm_execute:
	@echo "Are you sure you want to execute the target? [y/N] " && read ans && [ $${ans:-N} = y ]

init-all: confirm_execute
	@directory=$$(dirname $$(find . -type f -name reg_expand.sh )); \
	for dir in $$dirs; do \
		echo "Entering directory $$dir"; \
		$(MAKE) -C $$dir init; \
		popd; \
	done

run-all: confirm_execute
	@directory=$$(dirname $$(find . -type f -name reg_expand.sh )); \
	for dir in $$dirs; do \
		echo "Entering directory $$dir"; \
		$(MAKE) -C $$dir run; \
		popd; \
	done

dry-run-all: confirm_execute
	@dirs=$$(find . -type f -name reg_expand.sh -exec dirname {} \;); \
	for dir in $$dirs; do \
		echo "Entering directory $$dir"; \
		$(MAKE) -C $$dir dry-run; \
		popd; \
	done

clean-all: confirm_execute
	@dirs=$$(find . -type f -name reg_expand.sh -exec dirname {} \;); \
	for dir in $$dirs; do \
		echo "Entering directory $$dir"; \
		$(MAKE) -C $$dir clean; \
	done

