#!/bin/bash
# copy "full" or "one" to the current mv-params.

MV_FILES="tcp-bitrate-mv-params.json.template udp-bitrate-mv-params.json.template  udp-drop-mv-params.json.template"

for file in $MV_FILES; do
    if [ "$1" == "full" ]; then
       cp  $file ../
    elif [ "$1" == "one" ]; then
        cp "one-$file" ../$file
    else
        echo "usage: set one|full"
    fi
done

